#!/usr/bin/php
<?php

use Dotenv\Dotenv;

require_once 'vendor/autoload.php';

/**
 * @require libraries
 * dunst
 * dunstify
 */

$dotenv = Dotenv::createMutable('./');
$envs = $dotenv->load();

$action = $argv[1] ?? null;


switch ($action) {
    case 'play':
    case 'start':
        break;

    case 'stop':
        break;

    default:
        help();
        break;
}



function help()
{
    print_n(<<<HELP
    
    Name:
        radion - multi-function player for songs
    
    Description:     
        radion - it is multi-functional player for play song from resources (Youtube, files, etc)
    
    Examples:
    
    "radion play|start" - play song  
    "radion stop" - stop current playing song  
    "radion next" - play next song  
    "radion prev" - play prev song
    
    Author:
        Rahman Dikaev
    HELP);
}

function play($pid)
{
    global $urls;

    if ($pid) {
        exec('pkill -TERM -P ' . $pid);
    }

}

