#!/usr/bin/php
<?php

use Dotenv\Dotenv;
use Radion\Radion;

require_once 'vendor/autoload.php';

/**
 * @require libraries
 * dunst
 * dunstify
 */

// Initialize parser env variables
$dotenv = Dotenv::createMutable('./');
$envs = $dotenv->load();

$action = $argv[1] ?? null;

$radion = new Radion($envs);

switch ($action) {
    case 'play':
    case 'start':
        $radion->play();
        break;

    case 'stop':
        $radion->stop();
        break;

    case 'next':
        $radion->next();
        break;

    case 'prev':
        $radion->prev();
        break;

    case 'lists':
        printLists($radion->getAllLists());
        break;
    default:
        help();
        break;
}


function help()
{
    print_n(<<<HELP
    
    Name:
        radion - multi-function player for songs
    
    Description:     
        radion - it is multi-functional player for play song from resources (Youtube, files, etc)
    
    Examples:
    
    "radion play|start" - play song  
    "radion stop" - stop current playing song  
    "radion next" - play next song  
    "radion prev" - play prev song
    
    Author:
        Rahman Dikaev
    HELP);
}

